### ISSUE TITLE
Thinkpad L430 - unable to set thresholds

### ISSUE THREAD

**Issue by jseplae** [teleshoes/tpacpi-bat#3]
Hello, I'm reposting my issue here (from archlinux forums):
https://bbs.archlinux.org/viewtopic.php?id=158610

perl /usr/lib/perl5/vendor_perl/tpacpi-bat -v stopChargeThreshold 0 80
Call    : _SB.PCI0.LPC.EC.HKEY.BCSS 0x50
Response: Error: AE_NOT_FOUND

journalctl:
kernel: acpi_call: Cannot get handle: Error: AE_NOT_FOUND

This is on standard 3.7.9-1 kernel.

**Comment by hollunder** [comment]
Hi there. After quite some searching I found this bug report. The problem does not seem to be fixed in any general sense. Some things changed since 2013, which makes things harder for users to reproduce. Here is what I had to do for my L520 on Arch Linux.

install acpica (Version used: 20151218)

```
$ sudo acpidump -b -o dsdt.aml
```
(uncertain whether the -o had any sensible effect, dsdt.aml was empty but a lot of other files were generated)

```
$ iasl -d dsdt.dat
Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20151218-64
Copyright (c) 2000 - 2015 Intel Corporation

Input file dsdt.dat, Length 0xD170 (53616) bytes
ACPI: DSDT 0x0000000000000000 00D170 (v02 LENOVO TP-8G    00001230 INTL 20060912)
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed

Found 3 external control methods, reparsing with new information
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed
Disassembly completed
ASL Output:    dsdt.dsl - 438971 bytes

iASL Warning: There were 3 external control methods found during
disassembly, but additional ACPI tables to resolve these externals
were not specified. The resulting disassembler output file may not
compile because the disassembler did not know how many arguments
to assign to these methods. To specify the tables needed to resolve
external control method references, the -e option can be used to
specify the filenames. Note: SSDTs can be dynamically loaded at
runtime and may or may not be available via the host OS.
Example iASL invocations:
    iasl -e ssdt1.aml ssdt2.aml ssdt3.aml -d dsdt.aml
  }
    iasl -e dsdt.aml ssdt2.aml -d ssdt1.aml
    iasl -e ssdt*.aml -d dsdt.aml

In addition, the -fe option can be used to specify a file containing
control method external declarations with the associated method
argument counts. Each line of the file must be of the form:
    External (<method pathname>, MethodObj, <argument count>)
Invocation:
    iasl -fe refs.txt -d dsdt.aml
```
```
$ cat dsdt.dsl | grep \\\\_SB.PCI.*HKEY -o | uniq
\_SB.PCI0.LPCB.EC.HKEY
```
```
$ sudo vim /usr/bin/tpacpi-bat
```
Edit line 401:
```
  my $aslBase = `cat $psdev`;
```
to:
```
  my $aslBase = "\_SB.PCI0.LPCB.EC.HKEY";
```
Otherwise $aslBase would end up being "\_SB.HKEY".

**Comment by teleshoes** [comment]
weird, this should be working automatically these days. thanks for the update!

**Comment by hollunder** [comment]
Well, I thought it worked. The service started if the string was enclosed in " instead of '. Sadly I couldn't set a parameter, with the same error. When using the correct String enclosed in ' it still fails:
```
Jan 17 00:42:17 eeyore systemd[1]: tpacpi-bat.service: Main process exited, code=exited, status=255/n/a
Jan 17 00:42:17 eeyore systemd[1]: Failed to start sets battery thresholds.
Jan 17 00:42:17 eeyore systemd[1]: tpacpi-bat.service: Unit entered failed state.
Jan 17 00:42:17 eeyore systemd[1]: tpacpi-bat.service: Failed with result 'exit-code'.
Jan 17 00:42:17 eeyore tpacpi-bat[12605]: Error: AE_NOT_FOUND for ASL base: \_SB.PCI0.LPCB.EC.HKEY
Jan 17 00:42:17 eeyore tpacpi-bat[12605]: Error: AE_NOT_FOUND
```

With the stock code it also fails to start:
```
Jan 17 00:45:46 eeyore systemd[1]: Starting sets battery thresholds...
Jan 17 00:45:46 eeyore tpacpi-bat[12640]: Error: AE_NOT_FOUND for ASL base: \_SB.HKEY
Jan 17 00:45:46 eeyore tpacpi-bat[12640]: Error: AE_NOT_FOUND
Jan 17 00:45:46 eeyore systemd[1]: tpacpi-bat.service: Main process exited, code=exited, status=255/n/a
Jan 17 00:45:46 eeyore systemd[1]: Failed to start sets battery thresholds.
Jan 17 00:45:46 eeyore systemd[1]: tpacpi-bat.service: Unit entered failed state.
Jan 17 00:45:46 eeyore systemd[1]: tpacpi-bat.service: Failed with result 'exit-code'.
```

Any ideas as to what could be wrong?

**Comment by linrunner** [comment]
> The problem does not seem to be fixed in any general sense.

In fact it was solved in a general way, see line 391ff. But it seems Lenovo cannot stop making more strange exceptions in their UEFI/BIOSes ;-).

Is the newest BIOS installed?

Please show the output of

    grep '.*' /sys/class/power_supply/{BAT0,BAT1,AC,ADP0,ADP1}/device/path
    cat /sys/class/dmi/id/bios_version

**Comment by hollunder** [comment]
```
$ grep '.*' /sys/class/power_supply/{BAT0,BAT1,AC,ADP0,ADP1}/device/path
grep: /sys/class/power_supply/BAT0/device/path: No such file or directory
/sys/class/power_supply/BAT1/device/path:\_SB_.BAT1
grep: /sys/class/power_supply/AC/device/path: No such file or directory
grep: /sys/class/power_supply/ADP0/device/path: No such file or directory
grep: /sys/class/power_supply/ADP1/device/path: No such file or directory
```

```
$ cat /sys/class/dmi/id/bios_version
8GET46WW (1.23 )
```

According to the lenovo page, 1.23 is the latest version: http://support.lenovo.com/at/de/downloads/migr-77079

**Comment by linrunner** [comment]
Yes, it's the latest BIOS for your machine. 

ASL base auto detection does not work under the above conditions. Sorry, it seems you'll have to live with your workaround.

Just for reference the expected output (X220, same hardware gen):

    /sys/class/power_supply/BAT0/device/path:\_SB_.PCI0.LPC_.EC__.BAT0
    /sys/class/power_supply/AC/device/path:\_SB_.PCI0.LPC_.EC__.AC__

**Comment by hollunder** [comment]
Sadly my workaround doesn't work.

Can't it be made to work with this instead?
```
$ ls /sys/devices/platform/smapi/BAT0/
barcoding             design_voltage   inhibit_charge_minutes  remaining_capacity          state
charging_max_current  dump             installed               remaining_charging_time     stop_charge_thresh
charging_max_voltage  first_use_date   last_full_capacity      remaining_percent           temperature
chemistry             force_discharge  manufacture_date        remaining_percent_error     voltage
current_avg           group0_voltage   manufacturer            remaining_running_time
current_now           group1_voltage   model                   remaining_running_time_now
cycle_count           group2_voltage   power_avg               serial
design_capacity       group3_voltage   power_now               start_charge_thresh
```

**Comment by linrunner** [comment]
You should try all known ASL bases from the pre autodetection era --> https://github.com/teleshoes/tpacpi-bat/blob/ba20013cf5801edc4325f35b4afdf04da992fd60/tpacpi-bat#L42

And watch your perl syntax. Correct syntax is:

    my $aslBase = '\_SB.PCI0.   ';

**Comment by hollunder** [comment]
I have tried them all, without success.

I am unfamiliar with pearl but I corrected the typo above. Your example contains three spaces in the string, are they required?

**Comment by linrunner** [comment]
Try this old version of the script --> https://github.com/teleshoes/tpacpi-bat/blob/ba20013cf5801edc4325f35b4afdf04da992fd60/tpacpi-bat

**Comment by hollunder** [comment]
It fails with:
```
Jan 17 16:19:41 eeyore systemd[1]: Starting Set battery charge thresholds using tpacpi-bat...
Jan 17 16:19:41 eeyore tp-battery-mode[6498]: Error: no ASL base found
Jan 17 16:19:41 eeyore tp-battery-mode[6498]: Error: no ASL base found
```

**Comment by linrunner** [comment]
Then you're out of luck finally.

**Comment by hollunder** [comment]
Ok, thanks for your help. I guess I will try to use tp_smapi more directly through /sys/devices/platform/smapi/BAT0/. I guess that should allow to at least set the charge threshholds.

**Comment by N46AN** [comment]
Alternate method for extracting DSDT table:
```
sudo cat /sys/firmware/acpi/tables/DSDT > dsdt.aml
iasl -d dsdt.aml
cat dsdt.dsl | grep \\\\_SB\.PCI.*HKEY -o | uniq
```

**Comment by teleshoes** [comment]
thanks!

**Comment by joelmarty** [comment]
Hi everyone,

I tried running the script on a Lenovo Y50-70 (not a thinkpad yes but it does have the battery limit) and I get the AE_NOT_FOUND error. I stumbled upon this thread and tried the detect command which returns nothing, there is no "*HKEY" entry in my dsdt at all.

Does anyone know how I could find which function would allow me to set the battery threshold? i.e.: how did you find the "HKEY" function was the one to use in the first place?

**Comment by teleshoes** [comment]
you hit the nail on the head: the Y50 is not a thinkpad. it therefore almost certainly does not have this thinkpad-only ACPI interface, and so you wont be able to find it through any method.

lenovo might have an interface hiding somewhere in there, but youd have to spend quite a lot of time reverse engineering (on windows) to discover anything useful. doing this without any documentation is extremely unlikely to yield any results, so id suggest begging lenovo for docs (which is also unlikely to yield any results).

good luck!
